[phases.setup]
nixPkgs = ["nodejs", "python311", "pip"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build:staging",
  "mkdir -p backend_temp/app/static",
  "cp -r dist/* backend_temp/app/static/",
  "cd backend_temp && pip install -r requirements-minimal.txt"
]

[start]
cmd = "cd backend_temp && python start.py"
