[build]
  command = "npm run build:staging"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Environment-specific variables for staging
[context.deploy-preview]
  command = "npm run build:staging"

[context.branch-deploy]
  command = "npm run build:staging"

[context.dev]
  command = "npm run build:staging"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 