# Railway Configuration for Single Service Full Stack
# One service that builds frontend and runs backend

[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build:staging && mkdir -p backend/app/static && cp -r dist/* backend/app/static/ && cd backend && pip install -r requirements-minimal.txt"
watchPatterns = ["src/**/*", "package.json", "package-lock.json", "backend/**/*"]

[build.nixpacks]
providers = ["nodejs", "python"]
nodejsVersion = "18"
pythonVersion = "3.11"

[deploy]
startCommand = "cd backend && python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PYTHON_VERSION = "3.11"
ENVIRONMENT = "production"
DEBUG = "false"
HOST = "0.0.0.0"
PORT = "8000"
WORKERS = "1"
ENABLE_METRICS = "false"
LOG_LEVEL = "INFO"
LOG_FORMAT = "json"
SECRET_KEY = "railway-staging-secret-key-change-in-production"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
CORS_ORIGINS = "*"
CORS_ALLOW_CREDENTIALS = "false"
SUPABASE_URL = "https://placeholder.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "placeholder-key"
SUPABASE_ANON_KEY = "placeholder-key"
REDIS_URL = "redis://localhost:6379/0"
