# Railway configuration for BeSunny.ai Frontend Service
# This service will be deployed with root directory set to / (root)
# The React code is in src/ and will be built from the root directory

[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile.frontend.railway"

[build.environment]
NODE_ENV = "production"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 30
