[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile.backend"

# Docker build configuration
[build.docker]
enabled = true

# Health check configuration - optimized for reliability
[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30

# Environment configuration
[deploy.environment]
ENVIRONMENT = "production"
DEBUG = "false"
