# Railway configuration for BeSunny.ai Full Stack
# Deploying both frontend and backend services

# Default service (backend)
[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile.backend"

[build.environment]
ENVIRONMENT = "production"
DEBUG = "false"
HOST = "0.0.0.0"
PORT = "8000"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30

# Frontend service
[[services]]
name = "besunny-frontend"
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile.frontend.railway"

[services.besunny-frontend.build.environment]
NODE_ENV = "production"

[services.besunny-frontend.deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 30
