[build]
builder = "nixpacks"
buildCommand = "npm run build:staging"
watchPatterns = ["src/**/*", "package.json", "package-lock.json"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"

# Explicitly ignore backend directory for frontend deployment
[build.ignore]
paths = ["backend/**/*", "supabase/**/*", "database/**/*"]
