# Railway Configuration for Single Service Full Stack
# One service that builds frontend and runs backend

[build]
builder = "nixpacks"
buildCommand = "chmod +x build-for-railway.sh && ./build-for-railway.sh"
watchPatterns = ["src/**/*", "package.json", "package-lock.json", "backend/**/*"]

[build.nixpacks]
providers = ["nodejs", "python"]

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PYTHON_VERSION = "3.11"
