# Railway Frontend Service Configuration
# This file is specifically for the frontend service

[deploy]
startCommand = "npx serve -s dist -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

# Frontend build configuration
[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:production"
watchPatterns = ["src/**/*", "package.json", "vite.config.ts"]

# Source directory for frontend
[build.source]
path = "."
exclude = ["backend/**", "supabase/**", "database/**", "docs/**", "*.md", "Dockerfile*", "railway*.toml", "deploy-*.sh", ".railway/**", "**/deno.json", "**/*.deno"]

# Set working directory for the service
[deploy.workingDirectory]
path = "."

# Specify the output directory for the build
[build.output]
path = "dist"

# Force Node.js detection and exclude Python/Deno files
[build.detection]
node = true
python = false
deno = false

# Environment variables for frontend
[deploy.envs]
NODE_ENV = "production"
ENVIRONMENT = "production"
VITE_APP_NAME = "BeSunny.ai"
VITE_APP_VERSION = "17.0.0"
VITE_ENVIRONMENT = "production"
# This will be set to your backend service URL
VITE_PYTHON_BACKEND_URL = "https://your-backend-service.railway.app"
