# Railway Multi-Service Configuration
# This file defines both frontend and backend services explicitly

# Frontend Service Configuration
[[services]]
name = "frontend"
type = "web"

[services.build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:production"
watchPatterns = ["src/**/*", "package.json", "vite.config.ts"]

[services.build.source]
path = "."
exclude = ["backend/**", "supabase/**", "database/**", "docs/**", "*.md", "Dockerfile*", "railway*.toml", "deploy-*.sh", ".railway/**"]

[services.build.output]
path = "dist"

[services.build.detection]
node = true
python = false

[services.deploy]
startCommand = "npx serve -s dist -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
workingDirectory = "."

[services.envs]
NODE_ENV = "production"
ENVIRONMENT = "production"
VITE_APP_NAME = "BeSunny.ai"
VITE_APP_VERSION = "17.0.0"
VITE_ENVIRONMENT = "production"
VITE_PYTHON_BACKEND_URL = "https://your-backend-service.railway.app"

# Backend Service Configuration
[[services]]
name = "backend"
type = "web"

[services.build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
watchPatterns = ["**/*.py", "requirements.txt"]

[services.build.source]
path = "."
exclude = ["src/**", "public/**", "package*.json", "vite.config.ts", "tailwind.config.ts", "tsconfig*.json", "*.md", "Dockerfile*", "railway*.toml", "deploy-*.sh", ".railway/**", "node_modules/**", "dist/**"]

[services.build.detection]
python = true
node = false

[services.deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
workingDirectory = "backend"

[services.envs]
PYTHON_VERSION = "3.11"
ENVIRONMENT = "production"
DEBUG = "false"
HOST = "0.0.0.0"
PORT = "$PORT"
WORKERS = "1"
ENABLE_METRICS = "false"
LOG_LEVEL = "INFO"
LOG_FORMAT = "json"
SECRET_KEY = "railway-staging-secret-key-change-in-production"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
CORS_ORIGINS = "*"
CORS_ALLOW_CREDENTIALS = "false"
SUPABASE_URL = "https://placeholder.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "placeholder-key"
SUPABASE_ANON_KEY = "placeholder-key"
REDIS_URL = "redis://localhost:6379/0"
