# Railway Configuration - Using Docker for deployment
# Since Railway keeps auto-generating Dockerfiles, we'll use our own

[deploy]
startCommand = "python test_app_v4.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PYTHON_VERSION = "3.11"
ENVIRONMENT = "production"
DEBUG = "false"
HOST = "0.0.0.0"
PORT = "8000"
WORKERS = "1"
ENABLE_METRICS = "false"
LOG_LEVEL = "INFO"
LOG_FORMAT = "json"
SECRET_KEY = "railway-staging-secret-key-change-in-production"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
CORS_ORIGINS = "*"
CORS_ALLOW_CREDENTIALS = "false"
SUPABASE_URL = "https://placeholder.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "placeholder-key"
SUPABASE_ANON_KEY = "placeholder-key"
REDIS_URL = "redis://localhost:6379/0"
