[build]
builder = "nixpacks"
buildCommand = "echo 'Using Nixpacks source building'"

# Force source building, ignore any Dockerfiles
[build.ignore]
files = ["Dockerfile*", "docker-compose*.yml", "docker/*"]

# Explicitly disable Docker detection
[build.docker]
enabled = false

# Health check configuration
[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
