# Railway configuration for BeSunny.ai Backend
# Focus on getting the backend working first

[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile.backend"

# Backend environment
[build.environment]
ENVIRONMENT = "production"
DEBUG = "false"

# Backend deployment
[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30
