# Railway configuration for BeSunny.ai Full Stack
# Deploying both frontend and backend services

# Backend service (default)
[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile.backend"

# Backend environment
[build.environment]
ENVIRONMENT = "production"
DEBUG = "false"

# Backend deployment
[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30

# Frontend service
[[services]]
name = "besunny-frontend"
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile.frontend.railway"

[services.besunny-frontend.build.environment]
NODE_ENV = "production"

[services.besunny-frontend.deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 30
