version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.railway
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 512M

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
    deploy:
      resources:
        limits:
          memory: 1G
