version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.railway
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 512M

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.railway
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
    deploy:
      resources:
        limits:
          memory: 1G
