version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_RAILWAY_BACKEND_URL=http://localhost:8000
    networks:
      - besunny-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./backend:/app
    networks:
      - besunny-network

networks:
  besunny-network:
    driver: bridge
