name: Attendee Meeting Polling

on:
  schedule:
    # Run every 2 minutes
    - cron: '*/2 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  poll-meetings:
    runs-on: ubuntu-latest
    
    steps:
    - name: Poll Attendee Meetings
      run: |
        # Call the consolidated attendee service
        curl -X POST \
          -H "Content-Type: application/json" \
          "${{ secrets.SUPABASE_URL }}/functions/v1/attendee-service/poll-all"
      
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

    - name: Handle failure
      if: failure()
      run: |
        echo "Polling failed"
        # Add notification logic here if needed

    - name: Handle success
      if: success()
      run: |
        echo "Polling completed successfully" 