name: Refresh Google OAuth Tokens

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  refresh-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function to refresh tokens
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            "${{ secrets.REFRESH_GOOGLE_TOKEN_URL }}" 